### PR TITLE
Build arm64 docker images for Backend and Front end

### PR DESCRIPTION
**Pull request by IMPranshu**
This PR takes care of the https://github.com/bmcgonag/quant-ux-docker/issues/8 issue opened by me.

I have built and pushed arm64 images of both the Front-end and the Backend. The backed image was built with the original DockerFile without any issues. For the front end, a minor change has to be done in the Dockerfile and the arm64 image was built successfully.

https://hub.docker.com/repository/docker/impranshu/quant-ux-fe/tags?page=1&ordering=last_updated

https://hub.docker.com/repository/docker/impranshu/quant-ux-be/tags?page=1&ordering=last_updated

Now arm64 images can be built from the official repo as well and can be pushed to Docker Hub.

### CODE REVIEW

**Comment by bmcgonag** [comment]
I'm having a rough week. I literally did this yesterday for #8 and just now looked at this and realized you already did the same thing I did.  I 1000% appreciate you doing this. I'm kicking myself for spending a couple of hours going through builds on the front-end getting the necessary extra packages added.

**Review by bmcgonag — COMMENTED** [review]
This looks better than mine for certain.

**Comment by bmcgonag** [comment]
I merged this, 1. because it's better than what I did, and 2. I'd love to just build once. What I'm trying to understand is whether this can be built just once?  Do I need to pass it a --platform flag still in order to ensure the arm64 build?  Seems like I would.

**Comment by IMPranshu** [comment]
> I merged this, 1. because it's better than what I did, and 2. I'd love to just build once. What I'm trying to understand is whether this can be built just once? Do I need to pass it a --platform flag still in order to ensure the arm64 build? Seems like I would.

Correct. In order to build an arm64 `--platform` flag must be used. 
I think both can be built in one go, will have to modify the docker image a bit, but can be done.

**Pull request merged**
